// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-kGA9euQYxjcDA4WoIX8zpZcrOjSJ9E',
    appId: '1:59250765831:web:a3634007387ede47ff3aa2',
    messagingSenderId: '59250765831',
    projectId: 'fir-crud-operations-b1f34',
    authDomain: 'fir-crud-operations-b1f34.firebaseapp.com',
    storageBucket: 'fir-crud-operations-b1f34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjoqmZD9xJZEWq4jcxe2p0i96Z_qb9O-E',
    appId: '1:59250765831:android:765230964f9890fdff3aa2',
    messagingSenderId: '59250765831',
    projectId: 'fir-crud-operations-b1f34',
    storageBucket: 'fir-crud-operations-b1f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_nUlIxylAtawJ5DUJLuj3eVWiSDeR4Js',
    appId: '1:59250765831:ios:6081d42f8705b34bff3aa2',
    messagingSenderId: '59250765831',
    projectId: 'fir-crud-operations-b1f34',
    storageBucket: 'fir-crud-operations-b1f34.appspot.com',
    iosBundleId: 'com.example.firebaseCrudOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_nUlIxylAtawJ5DUJLuj3eVWiSDeR4Js',
    appId: '1:59250765831:ios:af364c2ee105a2c6ff3aa2',
    messagingSenderId: '59250765831',
    projectId: 'fir-crud-operations-b1f34',
    storageBucket: 'fir-crud-operations-b1f34.appspot.com',
    iosBundleId: 'com.example.firebaseCrudOperations.RunnerTests',
  );
}
